### ISSUE TITLE
Logging outside of hangfire job throws on missing PerformContext

### ISSUE THREAD

**Issue by SDEBEUL** [AnderssonPeter/Hangfire.Console.Extensions#1]
Hi Peter,

Nice little extension!
I ran into a small issue when logging outside of a hangfire job. (Where there is no performContext).
It trows on enriching with the background jobid. 
I understand this is due to asyncLocalLogFilter.Get()  returning null.

` /// <inheritdoc />
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            // Create property value with PerformContext and put as "PerformContext"
            var prop = new LogEventProperty(
                "PerformContext", new PerformContextValue { PerformContext = asyncLocalLogFilter.Get() }
            );
            logEvent.AddOrUpdateProperty(prop);
        }`

So as a test I added a null check on it,  and then just return from this Enrich method.
But then I'm in the situation that events written to the hangfire console don't end up in any other sink that uses property's
(SEQ in my case)

Would you have any insight on this?
br

**Comment by AnderssonPeter** [comment]
Could you add some failure logging and check what serilog says?
`Serilog.Debugging.SelfLog.Enable(Console.Error);` or 
```
if (!Directory.Exists("logs"))
{
    Directory.CreateDirectory("logs");
}
var file = File.AppendText("logs/SerilogErrors.log");
SelfLog.Enable(TextWriter.Synchronized(file));
```

**Comment by AnderssonPeter** [comment]
Just a guess but would using the following solve the issue
```c#
/// <inheritdoc />
public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
{
    // Create property value with PerformContext and put as "PerformContext"
    var context = asyncLocalLogFilter?.Get();
    if (context != null) {
        logEvent.AddOrUpdateProperty(new LogEventProperty(
            "PerformContext", new PerformContextValue { PerformContext = context }
        ));    
    }
}
```
???

**Comment by SDEBEUL** [comment]
Peter thanks for the quick reply.

What you did was exactly what I tried without success.

Your tip about the serilog internal logging did help me out!
It fails on serialization. Google then lead me to this.
[https://discuss.hangfire.io/t/serilog-seq-with-hangfire-console/7428/2](bug topic)
100% match with my issue.

I still kept the null check as not to add the property when we are not in a hangfire job.

Let me create a pull request if your willing to update master and nuget.

**Comment by AnderssonPeter** [comment]
I have Merged you solution, but i think i have a better solution to logging the `PerformingContext`, that i need to do some testing with! so i wont be able to create a new nuget today.

**Comment by AnderssonPeter** [comment]
Version 1.0.1 is up on nuget now, with some luck it will fix both of your issues.

**Comment by SDEBEUL** [comment]
Peter,
Thanks for your time. But I think the latest commit broke your code.
I did a fresh clone of the project. Starting the sampleWithSerilog project does not render anything in the hangfire console.
(Only the progress bar no logs)

br

**Comment by AnderssonPeter** [comment]
Ahh i know what i did to break it, i will try to fix it later today!

**Comment by AnderssonPeter** [comment]
A new version has been uploaded, hope it works as expected!

**Comment by SDEBEUL** [comment]
Yes this works!
