### ISSUE TITLE
[Q] Can't get this to work and log to the Console UI within Hangfire

### ISSUE THREAD

**Issue by robjakedorsett** [AnderssonPeter/Hangfire.Console.Extensions#11]
Hey.

Might be me, but I'm using .net 7, Hangfire 1.8.3 and I cannot get this to work.

I'm configuring it in my program.cs
`builder.Services.AddHangfireConsoleExtensions();`

But I can't see any logs appearing within the hangfire jobs.

I'm using `Microsoft.Extensions.Logging.ILogger<T>`

Any ideas?  Just no logs are outputting.

**Comment by AnderssonPeter** [comment]
If you check out this repo and change the examples to .net 7, does it work then?

If yes then it's most likely in your project, if not then it might be a bug.

**Comment by robjakedorsett** [comment]
Thanks, I've just checked out and created a new project (NET7) and the example seemed to have worked.

I've cross referenced and appears it was an issue with not adding UseConsole() & the ordering of the dependencies 🤦 

Thanks @AnderssonPeter 

Is it any interest to you to have the NET7 example within the code base? I can PR in if so, just .net 7 is slightly different to core3.1 in regards to the program/startup classes

**Comment by AnderssonPeter** [comment]
I don't think i need a PR, I will port over all the examples when .net 8 is released, but thanks for the offer.
