### ISSUE TITLE
This will always return `Enqueued`, Need to use the last history not the first

### ISSUE THREAD

**Issue by y-weiner** [AnderssonPeter/Hangfire.Console.Extensions#12]
https://github.com/AnderssonPeter/Hangfire.Console.Extensions/blame/4131d45c202f15629a5e976e449d5f4107986275/Hangfire.Console.Extensions/JobManager.cs#L51C71-L51C71

**Comment by AnderssonPeter** [comment]
Could you provide a PR?

**Comment by AnderssonPeter** [comment]
Thanks for the PR a 1.1.0 version has been uploaded that contains your fix and some other goodies!
If the issue still exists after 1.1.0 please reopen the issue!

**Comment by AnderssonPeter** [comment]
Sorry I forgot to add you name in the release notes when I uploaded the nuget, but it will be there in the next version of the nuget package.
