### ISSUE TITLE
Consider migrating from Hangfire.Console package to IdentityStream.Hangfire.Console

### ISSUE THREAD

**Issue by rossknudsen** [AnderssonPeter/Hangfire.Console.Extensions#14]
Hangfire.Console seems to be abandoned and has been recently forked and republished under IdentityStream.Hangfire.Console with a number of improvements.  Would you consider migrating to this package?

**Comment by AnderssonPeter** [comment]
Hi I'm aware of the fork, and will create 2 new packages that target the new fork when I get some time.

**Comment by AnderssonPeter** [comment]
@rossknudsen the work is more or less done, I'm just waiting for the 
permission to use the chosen name before I upload the packages to nuget.org

**Comment by rossknudsen** [comment]
Any luck with the above?

**Comment by AnderssonPeter** [comment]
@rossknudsen sadly I can't create a nugget with their company name in it, as nugget.org it self blocks this.. so for now I'm a bit unsure what name I should pick that would make sense..

**Comment by rossknudsen** [comment]
Would you just bump a major version for this package? Possibly go through a prerelease first?

**Comment by AnderssonPeter** [comment]
I'm not fond of that solution as it would force existing users to change a nugget to get the latest features.

**Comment by rossknudsen** [comment]
How about teaching out to the maintainers of IdentityStream.Hangfire.Console and asking them to fork this repo and release IdentityStream.Hangfire.Console.Extensions?  Presumably that was the NuGet package you wanted to create.

**Comment by AnderssonPeter** [comment]
I asked for a API key restricted to only that package, but they didn't like that idea.

**Comment by rossknudsen** [comment]
> I'm not fond of that solution as it would force existing users to change a nugget to get the latest features.

Not 100% sure what the issue is exactly.  Presumably people are referencing this Nuget package directly in their projects.  Most of the time people would target a specific version (e.g. `1.1.0`) rather than a wildcard version.  Under that assumption, they'd need to explicitly change their code to use the new version whatever increment you use (IMO a major version increment matches what IdentityStream team did).

I think updating this project (`Hangfire.Console.Extensions`) to point to a maintained dependency is a solid choice rather than trying to create another package.

**Comment by jherbert** [comment]
Agree with @rossknudsen here. A `2.0.0` release with a breaking change of removing `Hangfire.Console` and adding `IdentityStream.Hangfire.Console` dependency. Then call it out in the release notes.

**Comment by AnderssonPeter** [comment]
@rossknudsen @jherbert sorry for the huge delay, there are 2.0 packages on their way now that target IdentityStream.
