### ISSUE TITLE
Is v7 of Microsoft.Extensions.Logging really needed?

### ISSUE THREAD

**Issue by xumix** [AnderssonPeter/Hangfire.Console.Extensions#18]
It would be great if you could lower the version to 6.x for LTS oriented projects.
Thank you for your efforts!

**Comment by AnderssonPeter** [comment]
8 is lts now if I remember correctly, also 6 support ends this year. 

I'm sorry but I won't downgrade the minimum version.

**Comment by xumix** [comment]
But there is literally no difference in the code or dependencies when adding to newer SDK projects(for you specifically).
It would really help with gradual upgrading for us
