### ISSUE TITLE
Log messages are also rolled back with job transactions!

### ISSUE THREAD

**Issue by hidegh** [AnderssonPeter/Hangfire.Console.Extensions#22]
Never noticed before, but testing is simple.
We just need a job, 1 transaction scope that commits, and 1 that rolls back.

**Issues:**
- Logged message to the console disappears (also rolls back) in case of the 2nd transaction.
- Also until TX is committed, no logs are showing!

**Expected behavior:**
- Logging should be independent (separate transaction or outside transactions).
- Log messages shows up immediately (not just when TX commits)

---

![image](https://github.com/user-attachments/assets/2c635d4f-c268-4a0d-aa51-087b8b869bc3)

```cs
        jobProgress.WriteProgressLine(LogLevel.Information, "Before tran #1");
        using (var ts = TransactionScopeBuilder.New())
        {
            jobProgress.WriteProgressLine(LogLevel.Information, "Inside tran with commit");
            ts.Complete();
        }
        jobProgress.WriteProgressLine(LogLevel.Information, "After tran #1");

        jobProgress.WriteProgressLine(LogLevel.Information, "Before tran #2");
        using (var ts = TransactionScopeBuilder.New())
        {
            jobProgress.WriteProgressLine(LogLevel.Information, "Inside tran without commit");
            // rollback: ts.Complete();
        }
        jobProgress.WriteProgressLine(LogLevel.Information, "After tran #2");
```

**Comment by AnderssonPeter** [comment]
Are you sure this is an issue with this nuget and not the underlying console nuget? From what I remember there is no transaction logic in the code of this nuget.
