### ISSUE TITLE
[Q] How do you filter what goes to console and what level?

### ISSUE THREAD

**Issue by xumix** [AnderssonPeter/Hangfire.Console.Extensions#9]
There is no configuration for Hangfire.Console in the sample project appsettings.json

For Example, I want `System.*`  be logged to console with `Warning` level but all my `App.*` logger be logged with `Debug` level

**Comment by AnderssonPeter** [comment]
Are you using it with serilog or without?

**Comment by AnderssonPeter** [comment]
In both cases its mor about configuring the logging framework instead, the built in logging framework allows youvto configure levels based on logger name, and serilog has a filter plugin you can use that archives the same thing.

**Comment by xumix** [comment]
> In both cases its more about configuring the logging framework instead, the built in logging framework allows you to configure levels based on logger name, and serilog has a filter plugin you can use that archives the same thing.

I'm useing the built-in logging with NLog on top, I've tried configuring it like this:
```
"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "OpenTracing": "Warning",
      "Jaeger": "Warning",
      "Microsoft": "Warning",
      "Microsoft.EntityFrameworkCore.Database.Command": "Information",
      "Hangfire": "Debug"
    },
    "Hangfire": {
      "Default": "Debug",
      "System": "Information",
      "OpenTracing": "Warning",
      "Jaeger": "Warning",
      "Microsoft": "Warning"
    }
```
But still got Trace messages in console

**Comment by AnderssonPeter** [comment]
Also have you tried to add that to my sample if it works there i think it's a problem with nlog?

**Comment by xumix** [comment]
> Well if i was guessing it would have been what you just wrote, i sadly dont know exactly what is wrong. if i where you i would enable debug symbols for system.logging and and step into a logging call.

https://github.com/AnderssonPeter/Hangfire.Console.Extensions/blob/master/Hangfire.Console.Extensions/HangfireLogger.cs#L20= maybe this is the problem?

**Comment by AnderssonPeter** [comment]
That might be the case, could you provide a pr?

**Comment by AnderssonPeter** [comment]
Closed du to inactivity, please reopen if needed!

**Comment by Abdruggi** [comment]
@xumix The ProviderAliasAttribute is missing on the HangfireLoggerProvider. Therefore, it is not possible to configure log levels to filter logs. I created a pr to fix that. 

https://github.com/AnderssonPeter/Hangfire.Console.Extensions/pull/15
